-- Exercicios novos da base compartilhada (coach_id null).
-- Todos com desenho do free-exercise-db, que e dominio publico: o app anima
-- alternando os quadros 0.jpg e 1.jpg da pasta.
-- Regravar e seguro: casa pelo nome e nao duplica.
insert into public.train_exercicios (coach_id, nome, grupo_muscular, video_url)
select null, v.nome, v.grupo,
       'https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/'||v.pasta||'/0.jpg'
  from (values
('Abdução de Quadril com Elástico','Glúteos','Monster_Walk'),
('Extensão de Quadril com Elástico','Glúteos','Hip_Extension_with_Bands'),
('Elevação Pélvica com Elástico','Glúteos','Hip_Lift_with_Band'),
('Adução de Quadril com Elástico','Adutores','Band_Hip_Adductions'),
('Flexão de Quadril com Elástico','Quadríceps','Hip_Flexion_with_Band'),
('Agachamento com Elástico','Quadríceps','Squats_-_With_Bands'),
('Panturrilha com Elástico','Panturrilha','Calf_Raises_-_With_Bands'),
('Bom dia com Elástico','Posterior de Coxa','Band_Good_Morning'),
('Rotação Externa com Elástico','Ombro','External_Rotation_with_Band'),
('Rotação Interna com Elástico','Ombro','Internal_Rotation_with_Band'),
('Abrir Elástico à Frente (Pull Apart)','Ombro','Band_Pull_Apart'),
('Elevação Lateral com Elástico','Ombro','Lateral_Raise_-_With_Bands'),
('Desenvolvimento com Elástico','Ombro','Shoulder_Press_-_With_Bands'),
('Crucifixo Inverso com Elástico','Ombro','Back_Flyes_-_With_Bands'),
('Remada Alta com Elástico','Ombro','Upright_Row_-_With_Bands'),
('Supino com Elástico','Peito','Bench_Press_-_With_Bands'),
('Crossover com Elástico','Peito','Cross_Over_-_With_Bands'),
('Tríceps Testa com Elástico','Tríceps','Band_Skull_Crusher'),
('Tríceps Sobre a Cabeça com Elástico','Tríceps','Speed_Band_Overhead_Triceps'),
('Agachamento Livre sem Peso','Quadríceps','Bodyweight_Squat'),
('Agachamento Isométrico na Parede','Quadríceps','Sit_Squats'),
('Afundo Estático (Split Squat)','Quadríceps','Split_Squats'),
('Flexão de Braço Inclinada','Peito','Incline_Push-Up'),
('Flexão de Braço Fechada','Tríceps','Push-Ups_-_Close_Triceps_Position'),
('Flexão de Braço Aberta','Peito','Push-Up_Wide'),
('Flexão com Pés Elevados','Peito','Push-Ups_With_Feet_Elevated'),
('Flexão para Prancha Lateral','Peito','Push_Up_to_Side_Plank'),
('Mergulho no Banco','Tríceps','Bench_Dips'),
('Barra Fixa Pronada em Casa','Costas','Pullups'),
('Elevação de Perna Lateral no Solo','Glúteos','Side_Leg_Raises'),
('Step-up com Elevação de Joelho','Glúteos','Step-up_with_Knee_Raise'),
('Nordic Curl (Flexão Nórdica)','Posterior de Coxa','Natural_Glute_Ham_Raise'),
('Subida no Degrau','Quadríceps','Bench_Jump'),
('Abdominal Bicicleta','Abdômen','Air_Bike'),
('Abdominal Reverso no Solo','Abdômen','Reverse_Crunch'),
('Dead Bug (Inseto Morto)','Abdômen','Dead_Bug'),
('Prancha Lateral com Apoio','Abdômen','Side_Bridge'),
('Escalador (Spider Crawl)','Abdômen','Spider_Crawl'),
('Vacuum Abdominal','Abdômen','Stomach_Vacuum'),
('Polichinelo (Star Jump)','Cardio','Star_Jump'),
('Agachamento com Salto','Quadríceps','Freehand_Jump_Squat'),
('Corrida Estacionária (Skipping)','Cardio','Fast_Skipping'),
('Minhoca (Inchworm)','Posterior de Coxa','Inchworm'),
('Gato e Camelo','Mobilidade','Cat_Stretch'),
('Postura da Criança','Mobilidade','Childs_Pose'),
('Báscula de Pelve em Pé','Mobilidade','Standing_Pelvic_Tilt'),
('Báscula de Pelve para Ponte','Mobilidade','Pelvic_Tilt_Into_Bridge'),
('Joelhos ao Peito','Mobilidade','Hug_Knees_To_Chest'),
('Um Joelho ao Peito','Mobilidade','One_Knee_To_Chest'),
('Joelho Cruzando o Corpo','Mobilidade','Knee_Across_The_Body'),
('Alongamento de Piriforme (4 sentado)','Mobilidade','Ankle_On_The_Knee'),
('Alongamento de Glúteo Deitado','Mobilidade','Lying_Glute'),
('Alongamento de Flexor do Quadril','Mobilidade','Kneeling_Hip_Flexor'),
('Alongamento de Quadríceps de Lado','Mobilidade','On_Your_Side_Quad_Stretch'),
('Alongamento de Posterior 90/90','Mobilidade','90_90_Hamstring'),
('Alongamento de Posterior Sentado','Mobilidade','Seated_Floor_Hamstring_Stretch'),
('Alongamento de Panturrilha na Parede','Mobilidade','Calf_Stretch_Hands_Against_Wall'),
('Alongamento de Sóleo e Aquiles','Mobilidade','Standing_Soleus_And_Achilles_Stretch'),
('Alongamento de Adutores Deitado','Mobilidade','Lying_Bent_Leg_Groin'),
('Círculos de Ombro','Mobilidade','Shoulder_Circles'),
('Círculos de Braço','Mobilidade','Arm_Circles'),
('Círculos de Tornozelo','Mobilidade','Ankle_Circles'),
('Círculos de Quadril em Pé','Mobilidade','Standing_Hip_Circles'),
('Rotação de Tronco Sentado','Mobilidade','Spinal_Stretch'),
('Alongamento de Peitoral na Porta','Mobilidade','Chest_And_Front_Of_Shoulder_Stretch'),
('Alongamento de Dorsal em Pé','Mobilidade','Overhead_Lat'),
('Queixo ao Peito (cervical)','Mobilidade','Chin_To_Chest_Stretch'),
('Alongamento Lateral de Pescoço','Mobilidade','Side_Neck_Stretch'),
('Maior Alongamento do Mundo','Mobilidade','Worlds_Greatest_Stretch'),
('Avanço Cruzado (mobilidade)','Mobilidade','Crossover_Reverse_Lunge'),
('Cachorro Olhando para Baixo (Groiners)','Mobilidade','Groiners'),
('Alongamento de Punho Ajoelhado','Mobilidade','Kneeling_Forearm_Stretch'),
('Rolo no Quadríceps','Liberação','Quadriceps-SMR'),
('Rolo no Posterior de Coxa','Liberação','Hamstring-SMR'),
('Rolo na Panturrilha','Liberação','Calves-SMR'),
('Rolo na Banda Iliotibial','Liberação','Iliotibial_Tract-SMR'),
('Rolo no Adutor','Liberação','Adductor'),
('Rolo no Piriforme','Liberação','Piriformis-SMR'),
('Rolo na Lombar','Liberação','Lower_Back-SMR'),
('Rolo no Dorsal','Liberação','Latissimus_Dorsi-SMR'),
('Rolo nos Romboides','Liberação','Rhomboids-SMR'),
('Bolinha na Sola do Pé','Liberação','Foot-SMR'),
('Liberação do Tibial Anterior','Liberação','Anterior_Tibialis-SMR'),
('Liberação Cervical','Liberação','Neck-SMR'),
('Superman no Solo','Lombar','Superman'),
('Hiperextensão sem Banco','Lombar','Hyperextensions_With_No_Hyperextension_Bench'),
('Isometria Cervical Frente e Trás','Pescoço','Isometric_Neck_Exercise_-_Front_And_Back'),
('Isometria Cervical Lateral','Pescoço','Isometric_Neck_Exercise_-_Sides'),
('Elevação de Perna Deitado de Lado','Glúteos','Lying_Crossover'),
('Círculos de Quadril em Prono','Glúteos','Hip_Circles_prone'),
('Ponte de Glúteo no Solo','Glúteos','Butt_Lift_Bridge'),
('Pull Through na Polia','Glúteos','Pull_Through'),
('Face Pull','Ombro','Face_Pull'),
('Agachamento Goblet','Quadríceps','Goblet_Squat'),
('Agachamento na Cadeira (sentar e levantar)','Quadríceps','Chair_Squat'),
('Step-up com Halteres','Quadríceps','Dumbbell_Step_Ups'),
('Barra Fixa com Elástico','Costas','Band_Assisted_Pull-Up'),
('Swing com Kettlebell','Posterior de Coxa','One-Arm_Kettlebell_Swings'),
('Caminhada do Fazendeiro','Abdômen','Farmers_Walk')
  ) as v(nome, grupo, pasta)
 where not exists (select 1 from public.train_exercicios e
                    where e.coach_id is null and lower(e.nome) = lower(v.nome));
