-- ============================================================
-- MF Performance — Modelos de ficha e de periodização
-- Rode uma vez no Supabase (SQL Editor > New query > Run).
--
-- Duas tabelas simples. coach_id null = modelo que já vem no app
-- (todo mundo enxerga, ninguém edita). coach_id preenchido = modelo
-- que o treinador salvou, só ele enxerga.
--
-- O conteúdo fica em jsonb porque o modelo é lido inteiro de uma vez
-- e escrito inteiro de uma vez — não há consulta por exercício solto.
-- ============================================================

-- 1) Modelo de ficha (divisões + exercícios prescritos)
create table if not exists public.train_ficha_modelo (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid references public.profiles(id) on delete cascade,  -- null = base do app
  nome        text not null,
  objetivo    text,          -- Hipertrofia, Emagrecimento, Força, Adaptação
  nivel       text,          -- Iniciante, Intermediário, Avançado
  dias        int,           -- treinos por semana
  resumo      text,
  divisoes    jsonb not null default '[]'::jsonb,
  -- [{nome, ordem, exercicios:[{nome,tipo_serie,qtd_series,faixa_reps,intervalo_seg_min,ordem}]}]
  created_at  timestamptz not null default now()
);
create index if not exists train_ficha_modelo_coach_idx on public.train_ficha_modelo (coach_id);

alter table public.train_ficha_modelo enable row level security;
drop policy if exists train_ficha_modelo_read  on public.train_ficha_modelo;
drop policy if exists train_ficha_modelo_write on public.train_ficha_modelo;
create policy train_ficha_modelo_read on public.train_ficha_modelo
  for select using (coach_id is null or coach_id = auth.uid());
create policy train_ficha_modelo_write on public.train_ficha_modelo
  for all using (coach_id = auth.uid()) with check (coach_id = auth.uid());

-- 2) Modelo de periodização (fases + microciclos)
create table if not exists public.train_perio_modelo (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid references public.profiles(id) on delete cascade,
  nome        text not null,
  resumo      text,
  fases       jsonb not null default '[]'::jsonb,
  -- [{nome, modelo, foco, micros:[{nome,semanas,volume,intensidade,deload}]}]
  created_at  timestamptz not null default now()
);
create index if not exists train_perio_modelo_coach_idx on public.train_perio_modelo (coach_id);

alter table public.train_perio_modelo enable row level security;
drop policy if exists train_perio_modelo_read  on public.train_perio_modelo;
drop policy if exists train_perio_modelo_write on public.train_perio_modelo;
create policy train_perio_modelo_read on public.train_perio_modelo
  for select using (coach_id is null or coach_id = auth.uid());
create policy train_perio_modelo_write on public.train_perio_modelo
  for all using (coach_id = auth.uid()) with check (coach_id = auth.uid());

-- 3) Fichas prontas que já vêm no app (só as da base, sem duplicar)
delete from public.train_ficha_modelo where coach_id is null;
with src(nome,objetivo,nivel,dias,resumo,d) as (values
('AB — Iniciante (2x por semana)','Adaptação','Iniciante',2,'Corpo inteiro em dois treinos. Serve para quem está voltando ou nunca treinou: pouca máquina, muito padrão de movimento.','[["A — Corpo inteiro",[["Esteira","A",1,"8 min",0],["Agachamento Livre","V",3,"10-12",90],["Supino Reto com Halteres","V",3,"10-12",75],["Puxada Frente","V",3,"10-12",75],["Elevação Lateral","V",2,"12-15",45],["Prancha","V",3,"30 s",45]]],["B — Corpo inteiro",[["Bicicleta","A",1,"8 min",0],["Leg Press","V",3,"12-15",90],["Remada Baixa","V",3,"10-12",75],["Supino Inclinado com Halteres","V",3,"10-12",75],["Desenvolvimento com Halteres","V",2,"10-12",60],["Rosca Direta","V",2,"12",45],["Tríceps Corda","V",2,"12",45],["Abdominal Supra","V",3,"15",45]]]]'::jsonb),
('ABC — Hipertrofia (3x por semana)','Hipertrofia','Intermediário',3,'Clássico empurrar / puxar / pernas. Volume moderado e descanso de 60 a 90 segundos.','[["A — Peito, ombro e tríceps",[["Supino Reto","A",1,"15 leve",60],["Supino Reto","V",4,"8-10",90],["Supino Inclinado com Halteres","V",3,"10-12",75],["Crucifixo","V",3,"12-15",60],["Desenvolvimento com Halteres","V",3,"10-12",75],["Elevação Lateral","V",4,"12-15",45],["Tríceps Corda","V",3,"12-15",45],["Tríceps Testa","V",3,"10-12",60]]],["B — Costas e bíceps",[["Puxada Frente","A",1,"15 leve",60],["Barra Fixa","V",3,"até a falha",90],["Puxada Frente","V",4,"10-12",75],["Remada Curvada","V",4,"8-10",90],["Remada Baixa","V",3,"10-12",75],["Crucifixo Inverso","V",3,"15",45],["Rosca Direta","V",3,"10-12",60],["Rosca Martelo","V",3,"12",45]]],["C — Pernas e glúteo",[["Cadeira Extensora","A",1,"20 leve",60],["Agachamento Livre","V",4,"8-10",120],["Leg Press","V",4,"12-15",90],["Cadeira Extensora","V",3,"15",60],["Mesa Flexora","V",4,"12",60],["Stiff","V",3,"10-12",90],["Elevação Pélvica com Barra","V",3,"12",75],["Panturrilha em Pé","V",4,"15-20",45]]]]'::jsonb),
('ABCD — Hipertrofia avançada (4x por semana)','Hipertrofia','Avançado',4,'Divisão em quatro para quem já treina há mais de um ano. Volume alto por grupo e um dia só de ombro e abdômen.','[["A — Peito e tríceps",[["Supino Reto","A",1,"15 leve",60],["Supino Reto","V",4,"6-8",120],["Supino Inclinado","V",4,"8-10",90],["Crossover","V",3,"12-15",60],["Peck Deck (Voador)","V",3,"12-15",60],["Supino Fechado","V",3,"8-10",90],["Tríceps Barra na Polia","V",4,"10-12",60],["Tríceps Francês","V",3,"12",60]]],["B — Costas e bíceps",[["Puxada Frente","A",1,"15 leve",60],["Barra Fixa","V",4,"até a falha",90],["Remada Curvada","V",4,"6-8",120],["Puxada Triângulo","V",3,"10-12",75],["Remada Serrote","V",3,"10-12",75],["Pullover","V",3,"12-15",60],["Rosca Direta","V",4,"8-10",60],["Rosca Scott","V",3,"10-12",60],["Rosca Concentrada","V",3,"12",45]]],["C — Pernas",[["Cadeira Extensora","A",1,"20 leve",60],["Agachamento Livre","V",5,"6-8",150],["Agachamento Hack","V",4,"10-12",120],["Leg Press","V",4,"12-15",90],["Cadeira Extensora","V",4,"15",60],["Levantamento Terra Romeno","V",4,"8-10",120],["Mesa Flexora","V",4,"12",60],["Panturrilha no Leg","V",5,"15-20",45]]],["D — Ombro, glúteo e abdômen",[["Elevação Lateral","A",1,"20 leve",45],["Desenvolvimento com Barra","V",4,"8-10",90],["Elevação Lateral","V",4,"12-15",45],["Elevação Frontal","V",3,"12",45],["Crucifixo Inverso","V",4,"15",45],["Encolhimento (Trapézio)","V",4,"12-15",60],["Elevação Pélvica com Barra","V",4,"10-12",90],["Cadeira Abdutora","V",3,"15-20",45],["Abdominal na Polia","V",4,"15",45]]]]'::jsonb),
('Upper / Lower — Força (4x por semana)','Força','Intermediário',4,'Dois treinos de membros superiores e dois de inferiores. Cargas altas, poucas repetições e descanso longo.','[["Upper A — Força de empurrar",[["Supino Reto","A",2,"10 leve",90],["Supino Reto","V",5,"5",180],["Desenvolvimento com Barra","V",4,"6",150],["Remada Curvada","V",4,"6",150],["Barra Fixa","V",3,"até a falha",120],["Tríceps Testa","V",3,"8-10",90],["Rosca Direta","V",3,"8-10",90]]],["Lower A — Agachamento",[["Agachamento Livre","A",2,"8 leve",90],["Agachamento Livre","V",5,"5",210],["Leg Press","V",4,"8",150],["Levantamento Terra Romeno","V",4,"6-8",150],["Cadeira Flexora","V",3,"10-12",75],["Panturrilha em Pé","V",4,"12-15",60]]],["Upper B — Força de puxar",[["Puxada Frente","A",2,"12 leve",60],["Remada Cavalinho","V",5,"6",150],["Supino Inclinado","V",4,"6-8",150],["Puxada Supinada","V",4,"8",120],["Desenvolvimento Máquina","V",3,"8-10",90],["Rosca Martelo","V",3,"10",75],["Mergulho (Dips)","V",3,"até a falha",90]]],["Lower B — Terra",[["Hiperextensão Lombar","A",2,"12 leve",60],["Levantamento Terra","V",5,"3-5",210],["Agachamento Frontal","V",4,"6",150],["Afundo","V",3,"10 cada perna",120],["Mesa Flexora","V",3,"10-12",75],["Panturrilha Sentado","V",4,"15",60]]]]'::jsonb),
('ABC — Emagrecimento em circuito (3x por semana)','Emagrecimento','Iniciante',3,'Descanso curto para manter a frequência cardíaca alta, com cardio no fim de cada treino.','[["A — Inferiores em circuito",[["Esteira","A",1,"10 min",0],["Agachamento Livre","V",4,"15",30],["Leg Press","V",4,"15-20",30],["Afundo","V",3,"12 cada perna",30],["Cadeira Flexora","V",3,"15",30],["Elevação Pélvica","V",3,"15",30],["Esteira","V",1,"15 min",0]]],["B — Superiores em circuito",[["Remo Ergômetro","A",1,"8 min",0],["Puxada Frente","V",4,"15",30],["Supino Máquina","V",4,"15",30],["Remada Máquina","V",3,"15",30],["Elevação Lateral","V",3,"15",30],["Tríceps Corda","V",3,"15",30],["Rosca na Polia","V",3,"15",30],["Bicicleta","V",1,"15 min",0]]],["C — Corpo inteiro e core",[["Pular Corda","A",1,"5 min",0],["Agachamento Sumô","V",4,"15",30],["Flexão de Braço","V",4,"até a falha",30],["Remada Baixa","V",4,"15",30],["Desenvolvimento com Halteres","V",3,"15",30],["Prancha","V",3,"45 s",30],["Bicicleta no Solo","V",3,"20",30],["Escada","V",1,"12 min",0]]]]'::jsonb),
('Glúteo e pernas — 3x por semana','Hipertrofia','Intermediário',3,'Dois treinos de inferiores com foco em glúteo e um de superiores para equilibrar.','[["A — Glúteo e posterior",[["Abdução com Elástico","A",2,"20",45],["Elevação Pélvica com Barra","V",4,"10-12",90],["Levantamento Terra Sumô","V",4,"10",120],["Cadeira Flexora","V",4,"12-15",60],["Coice na Polia","V",3,"15 cada perna",45],["Cadeira Abdutora","V",4,"20",45],["Panturrilha em Pé","V",3,"15-20",45]]],["B — Quadríceps e glúteo",[["Cadeira Extensora","A",2,"20 leve",45],["Agachamento Livre","V",4,"10-12",120],["Agachamento Búlgaro","V",3,"12 cada perna",90],["Leg Press","V",4,"15",90],["Cadeira Extensora","V",3,"15",60],["Elevação Pélvica Unilateral","V",3,"12 cada perna",60],["Abdução em Pé","V",3,"20",45]]],["C — Superiores e core",[["Puxada Frente","A",1,"15 leve",60],["Puxada Frente","V",4,"10-12",75],["Remada Baixa","V",3,"12",60],["Supino Inclinado com Halteres","V",3,"12",60],["Elevação Lateral","V",4,"15",45],["Rosca Alternada","V",3,"12",45],["Tríceps Corda","V",3,"12-15",45],["Prancha","V",3,"45 s",45],["Abdominal Infra","V",3,"15",45]]]]'::jsonb)
)
insert into public.train_ficha_modelo (nome,objetivo,nivel,dias,resumo,divisoes)
select s.nome,s.objetivo,s.nivel,s.dias,s.resumo,
  (select jsonb_agg(jsonb_build_object(
     'nome', dv->>0,
     'ordem', di-1,
     'exercicios', (select jsonb_agg(jsonb_build_object(
         'nome', ex->>0,
         'tipo_serie', case ex->>1 when 'A' then 'Aquecimento' else 'Valida' end,
         'qtd_series', (ex->>2)::int,
         'faixa_reps', ex->>3,
         'intervalo_seg_min', (ex->>4)::int,
         'ordem', ei-1) order by ei)
       from jsonb_array_elements(dv->1) with ordinality t(ex,ei))
   ) order by di)
   from jsonb_array_elements(s.d) with ordinality u(dv,di))
from src s;

-- ============================================================
-- Pente fino pré-lançamento: a tela de cadastros repetidos agrupa por
-- primeiro nome, e isso junta homônimos. Aqui o e-mail entra na lista e
-- a fusão trava quando os dois cadastros têm login próprio.
-- (Aplicado como migração mfp_duplicados_email_e_trava_dois_logins.)
-- ============================================================
with src(nome,objetivo,nivel,dias,resumo,d) as (values
('Starting Strength — Rippetoe (3x por semana)','Força','Iniciante',2,'O programa de Mark Rippetoe: pouquíssimos exercícios, 3 séries de 5, e carga subindo em todo treino. Alterna A e B em dias não consecutivos. É o caminho mais curto para um iniciante ficar forte.','[["A — Agachamento, supino e terra",[["Agachamento Livre","A",2,"5 leve",120],["Agachamento Livre","V",3,"5",180],["Supino Reto","V",3,"5",180],["Levantamento Terra","V",1,"5",240],["Prancha","V",3,"45 s",60]]],["B — Agachamento, desenvolvimento e remada",[["Agachamento Livre","A",2,"5 leve",120],["Agachamento Livre","V",3,"5",180],["Desenvolvimento com Barra","V",3,"5",180],["Remada Curvada","V",3,"5",180],["Barra Fixa","V",3,"até a falha",120]]]]'::jsonb),
('StrongLifts 5x5 (3x por semana)','Força','Iniciante',2,'Cinco séries de cinco nos três levantamentos, alternando A e B. Some 2,5 kg por treino enquanto der. Volume maior que o Starting Strength, mesma lógica de progressão linear.','[["A — Agachamento, supino e remada",[["Agachamento Livre","A",2,"5 leve",90],["Agachamento Livre","V",5,"5",180],["Supino Reto","V",5,"5",180],["Remada Curvada","V",5,"5",180]]],["B — Agachamento, desenvolvimento e terra",[["Agachamento Livre","A",2,"5 leve",90],["Agachamento Livre","V",5,"5",180],["Desenvolvimento com Barra","V",5,"5",180],["Levantamento Terra","V",1,"5",240]]]]'::jsonb),
('Golden Six — Arnold Schwarzenegger (3x por semana)','Hipertrofia','Iniciante',1,'A rotina de iniciante da Enciclopédia do Fisiculturismo do Arnold: seis exercícios, corpo inteiro, três vezes por semana. Simples de propósito — o ganho vem de repetir e progredir.','[["Corpo inteiro — Golden Six",[["Agachamento Livre","A",1,"15 leve",90],["Agachamento Livre","V",4,"10",120],["Supino Reto","V",3,"10",120],["Barra Fixa","V",3,"até a falha",90],["Desenvolvimento com Barra","V",4,"10",90],["Rosca Direta","V",3,"10",75],["Abdominal Supra","V",3,"até a falha",45]]]]'::jsonb),
('Heavy Duty — Mike Mentzer (2x por semana)','Hipertrofia','Avançado',2,'Alta intensidade e volume mínimo: uma série válida por exercício, levada até a falha, com 4 a 7 dias entre treinos iguais. Exige aquecimento sério e alguém de olho. Não é para quem gosta de treinar todo dia.','[["A — Peito, costas e pernas",[["Peck Deck (Voador)","A",2,"12 leve",90],["Peck Deck (Voador)","V",1,"6-10 até a falha",180],["Supino Inclinado","V",1,"6-10 até a falha",180],["Pulldown","V",1,"6-10 até a falha",180],["Remada Curvada","V",1,"6-10 até a falha",180],["Agachamento Livre","A",2,"10 leve",120],["Agachamento Livre","V",1,"8-15 até a falha",240],["Panturrilha em Pé","V",1,"12-20 até a falha",90]]],["B — Ombro, braço e posterior",[["Elevação Lateral","A",2,"15 leve",60],["Elevação Lateral","V",1,"6-10 até a falha",180],["Crucifixo Inverso","V",1,"6-10 até a falha",180],["Tríceps Barra na Polia","V",1,"6-10 até a falha",180],["Mergulho (Dips)","V",1,"até a falha",180],["Rosca Direta","V",1,"6-10 até a falha",180],["Mesa Flexora","V",1,"8-12 até a falha",180],["Levantamento Terra Romeno","V",1,"8-12 até a falha",240]]]]'::jsonb),
('German Volume Training 10x10 (4x por semana)','Hipertrofia','Avançado',4,'O 10x10 que Charles Poliquin popularizou: dez séries de dez no exercício principal, com cerca de 60% de 1RM e descanso curto. Um par de movimentos opostos por sessão. Ciclo de 4 a 6 semanas, não mais.','[["A — Peito e costas",[["Supino Reto","A",2,"10 leve",60],["Supino Reto","V",10,"10",90],["Remada Curvada","V",10,"10",90],["Crucifixo Inclinado","V",3,"10-12",60],["Remada Baixa","V",3,"10-12",60]]],["B — Pernas e abdômen",[["Cadeira Extensora","A",2,"15 leve",60],["Agachamento Livre","V",10,"10",90],["Mesa Flexora","V",10,"10",90],["Panturrilha em Pé","V",3,"15-20",60],["Abdominal na Polia","V",3,"15",60]]],["C — Braços e ombro",[["Rosca Direta","A",2,"12 leve",45],["Rosca Scott","V",10,"10",90],["Tríceps Testa","V",10,"10",90],["Elevação Lateral","V",3,"12-15",60],["Face Pull","V",3,"15",60]]],["D — Costas e ombro",[["Puxada Frente","A",2,"12 leve",60],["Puxada Frente","V",10,"10",90],["Desenvolvimento com Halteres","V",10,"10",90],["Crucifixo Inverso","V",3,"15",60],["Encolhimento (Trapézio)","V",3,"12",60]]]]'::jsonb),
('5/3/1 com Boring But Big — Wendler (4x por semana)','Força','Intermediário',4,'Um levantamento principal por dia em ondas de 5, 3 e 1 repetição sobre 90% do seu máximo, seguido do complemento 5x10 na mesma barra. Ciclo de 4 semanas: 65-75-85%, 70-80-90%, 75-85-95% e descarga.','[["Dia 1 — Desenvolvimento",[["Desenvolvimento com Barra","A",2,"5 leve",90],["Desenvolvimento com Barra","V",3,"5/3/1 do ciclo",180],["Desenvolvimento com Barra","V",5,"10",90],["Puxada Frente","V",5,"10",90],["Rosca Direta","V",3,"12",60]]],["Dia 2 — Levantamento terra",[["Hiperextensão Lombar","A",2,"12 leve",60],["Levantamento Terra","V",3,"5/3/1 do ciclo",240],["Levantamento Terra","V",5,"10",120],["Mesa Flexora","V",5,"10",90],["Prancha","V",3,"60 s",60]]],["Dia 3 — Supino",[["Supino Reto","A",2,"8 leve",90],["Supino Reto","V",3,"5/3/1 do ciclo",180],["Supino Reto","V",5,"10",90],["Remada Curvada","V",5,"10",90],["Tríceps Corda","V",3,"12",60]]],["Dia 4 — Agachamento",[["Agachamento Livre","A",2,"5 leve",120],["Agachamento Livre","V",3,"5/3/1 do ciclo",240],["Agachamento Livre","V",5,"10",120],["Leg Press","V",5,"10",90],["Panturrilha em Pé","V",4,"15",45]]]]'::jsonb),
('PHUL — Força e hipertrofia (4x por semana)','Hipertrofia','Intermediário',4,'Dois dias pesados de 3 a 5 repetições e dois dias de volume de 8 a 15, dividindo superior e inferior. É a forma mais simples de treinar força e tamanho na mesma semana.','[["Superior — Força",[["Supino Reto","A",2,"8 leve",90],["Supino Reto","V",4,"3-5",180],["Remada Curvada","V",4,"3-5",180],["Supino Inclinado com Halteres","V",3,"6-10",120],["Puxada Frente","V",3,"6-10",120],["Desenvolvimento com Barra","V",3,"5-8",120],["Rosca Direta","V",3,"6-10",75],["Tríceps Testa","V",3,"6-10",75]]],["Inferior — Força",[["Cadeira Extensora","A",2,"15 leve",60],["Agachamento Livre","V",4,"3-5",210],["Levantamento Terra","V",3,"3-5",240],["Leg Press","V",3,"10-15",120],["Cadeira Flexora","V",4,"8-12",90],["Panturrilha em Pé","V",4,"8-12",60]]],["Superior — Hipertrofia",[["Supino Inclinado","A",2,"12 leve",60],["Supino Inclinado","V",4,"8-12",90],["Peck Deck (Voador)","V",3,"12-15",60],["Remada Serrote","V",4,"8-12",90],["Puxada Triângulo","V",3,"12-15",75],["Elevação Lateral","V",4,"12-20",45],["Rosca Alternada","V",3,"12-15",60],["Tríceps Corda","V",3,"12-15",60]]],["Inferior — Hipertrofia",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Frontal","V",4,"8-12",120],["Passada (Walking Lunge)","V",3,"12 cada perna",90],["Cadeira Extensora","V",4,"15-20",60],["Mesa Flexora","V",4,"12-15",75],["Elevação Pélvica com Barra","V",3,"10-12",90],["Panturrilha Sentado","V",5,"15-20",45]]]]'::jsonb),
('PHAT — Layne Norton (5x por semana)','Hipertrofia','Avançado',5,'Dois dias de potência com poucas repetições e três de hipertrofia com volume alto, cada grupo treinado duas vezes por semana. Programa exigente: só faz sentido com base e boa recuperação.','[["Dia 1 — Superior potência",[["Remada Curvada","A",2,"8 leve",90],["Remada Curvada","V",3,"3-5",180],["Puxada Supinada","V",2,"6-10",120],["Supino Reto","V",3,"3-5",180],["Supino Inclinado com Halteres","V",2,"6-10",120],["Desenvolvimento com Halteres","V",3,"6-10",120],["Rosca Direta","V",3,"6-10",75],["Tríceps Testa","V",3,"6-10",75]]],["Dia 2 — Inferior potência",[["Cadeira Extensora","A",2,"15 leve",60],["Agachamento Livre","V",3,"3-5",210],["Agachamento Hack","V",2,"6-10",150],["Levantamento Terra Romeno","V",3,"5-8",180],["Mesa Flexora","V",2,"6-10",90],["Panturrilha em Pé","V",3,"6-10",75]]],["Dia 3 — Costas e ombro",[["Puxada Frente","A",2,"12 leve",60],["Remada Cavalinho","V",4,"8-12",90],["Puxada Aberta","V",3,"10-15",75],["Remada Baixa","V",3,"12-15",75],["Pullover","V",2,"12-15",60],["Elevação Lateral","V",4,"12-20",45],["Crucifixo Inverso","V",3,"15-20",45],["Encolhimento (Trapézio)","V",3,"12-15",60]]],["Dia 4 — Inferior hipertrofia",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Livre","V",3,"8-12",120],["Leg Press","V",3,"12-15",90],["Cadeira Extensora","V",3,"15-20",60],["Stiff","V",3,"8-12",120],["Cadeira Flexora","V",3,"12-15",75],["Panturrilha em Pé","V",4,"12-15",60],["Panturrilha Sentado","V",3,"15-20",45]]],["Dia 5 — Peito e braço",[["Supino Inclinado","A",2,"12 leve",60],["Supino Inclinado","V",4,"8-12",90],["Crucifixo","V",3,"12-15",60],["Crossover","V",3,"15-20",45],["Rosca Scott","V",3,"12-15",60],["Rosca Martelo","V",3,"12-15",60],["Tríceps Corda","V",3,"12-15",60],["Tríceps Francês","V",3,"12-15",60]]]]'::jsonb),
('Push / Pull / Legs (6x por semana)','Hipertrofia','Avançado',6,'Empurrar, puxar e pernas, repetido duas vezes na semana. Cada grupo é treinado a cada 3 ou 4 dias, que é a frequência que a maior parte da literatura de hipertrofia recomenda quando o volume é alto.','[["Push A — Peito, ombro e tríceps",[["Supino Reto","A",2,"12 leve",60],["Supino Reto","V",4,"6-8",120],["Desenvolvimento com Halteres","V",3,"8-12",90],["Supino Inclinado com Halteres","V",3,"10-12",75],["Elevação Lateral","V",4,"12-15",45],["Tríceps Barra na Polia","V",3,"10-12",60],["Tríceps Francês","V",3,"12-15",60]]],["Pull A — Costas e bíceps",[["Puxada Frente","A",2,"12 leve",60],["Barra Fixa","V",4,"até a falha",120],["Remada Curvada","V",4,"6-8",120],["Remada Baixa","V",3,"10-12",75],["Face Pull","V",3,"15-20",45],["Rosca Direta","V",3,"8-12",60],["Rosca Martelo","V",3,"10-12",60]]],["Legs A — Ênfase quadríceps",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Livre","V",4,"6-8",180],["Leg Press","V",4,"10-12",120],["Passada (Walking Lunge)","V",3,"12 cada perna",90],["Cadeira Extensora","V",3,"15",60],["Panturrilha em Pé","V",4,"12-15",60]]],["Push B — Ombro em ênfase",[["Elevação Lateral","A",2,"20 leve",45],["Desenvolvimento com Barra","V",4,"6-8",120],["Supino Inclinado","V",4,"8-10",90],["Crossover","V",3,"12-15",60],["Elevação Lateral na Polia","V",4,"15",45],["Supino Fechado","V",3,"8-10",90],["Tríceps Corda","V",3,"12-15",60]]],["Pull B — Espessura de costas",[["Puxada Frente","A",2,"12 leve",60],["Remada Cavalinho","V",4,"8-10",120],["Puxada Triângulo","V",4,"10-12",75],["Remada Serrote","V",3,"10-12",75],["Crucifixo Inverso","V",3,"15-20",45],["Rosca Scott","V",3,"10-12",60],["Rosca Inversa","V",3,"12-15",60]]],["Legs B — Ênfase posterior e glúteo",[["Mesa Flexora","A",2,"15 leve",60],["Levantamento Terra Romeno","V",4,"6-8",180],["Elevação Pélvica com Barra","V",4,"8-12",120],["Cadeira Flexora","V",4,"12-15",75],["Agachamento Búlgaro","V",3,"10 cada perna",90],["Panturrilha Sentado","V",4,"15-20",45]]]]'::jsonb),
('HST — Hypertrophy Specific Training (3x por semana)','Hipertrofia','Intermediário',1,'Corpo inteiro três vezes por semana, com as repetições caindo a cada bloco de duas semanas: 15, depois 10, depois 5, e as cargas subindo a cada sessão. Fecha com uma ou duas semanas leves antes de recomeçar.','[["Corpo inteiro — bloco de 15, 10 ou 5",[["Esteira","A",1,"6 min",0],["Agachamento Livre","V",2,"15 / 10 / 5 do bloco",120],["Levantamento Terra Romeno","V",2,"15 / 10 / 5 do bloco",120],["Supino Reto","V",2,"15 / 10 / 5 do bloco",120],["Remada Curvada","V",2,"15 / 10 / 5 do bloco",120],["Desenvolvimento com Halteres","V",2,"15 / 10 / 5 do bloco",90],["Puxada Frente","V",2,"15 / 10 / 5 do bloco",90],["Rosca Direta","V",1,"15 / 10 / 5 do bloco",60],["Tríceps Corda","V",1,"15 / 10 / 5 do bloco",60],["Panturrilha em Pé","V",2,"15-20",45]]]]'::jsonb),
('FST-7 — Hany Rambod (5x por semana)','Hipertrofia','Avançado',5,'Treino pesado normal e, no fim de cada grupo, sete séries do isolador com 30 a 45 segundos de descanso. A ideia é encher o músculo de sangue e alongar a fáscia. Use nos grupos que você quer priorizar.','[["Dia 1 — Peito e bíceps",[["Supino Reto","A",2,"12 leve",60],["Supino Inclinado","V",4,"8-12",90],["Supino Reto com Halteres","V",3,"8-12",90],["Peck Deck (Voador)","V",7,"10-12",40],["Rosca Direta","V",3,"8-12",75],["Rosca Scott","V",7,"10-12",40]]],["Dia 2 — Costas e panturrilha",[["Puxada Frente","A",2,"12 leve",60],["Barra Fixa","V",3,"até a falha",120],["Remada Curvada","V",4,"8-12",90],["Remada Serrote","V",3,"10-12",75],["Pulldown","V",7,"10-12",40],["Panturrilha em Pé","V",7,"12-15",40]]],["Dia 3 — Ombro e tríceps",[["Elevação Lateral","A",2,"20 leve",45],["Desenvolvimento com Halteres","V",4,"8-12",90],["Elevação Lateral","V",7,"12-15",40],["Crucifixo Inverso","V",3,"15",45],["Supino Fechado","V",3,"8-12",90],["Tríceps Corda","V",7,"10-12",40]]],["Dia 4 — Quadríceps",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Livre","V",4,"8-12",150],["Agachamento Hack","V",3,"10-12",120],["Leg Press","V",3,"12-15",90],["Cadeira Extensora","V",7,"12-15",40]]],["Dia 5 — Posterior, glúteo e abdômen",[["Mesa Flexora","A",2,"15 leve",60],["Levantamento Terra Romeno","V",4,"8-12",120],["Cadeira Flexora","V",3,"10-12",75],["Mesa Flexora","V",7,"10-12",40],["Elevação Pélvica com Barra","V",4,"10-12",90],["Abdominal na Polia","V",4,"15",45]]]]'::jsonb),
('Joelho — retorno progressivo (3x por semana)','Reabilitação','Iniciante',3,'Para dor femoropatelar e volta de lesão de joelho já liberada. Começa em cadeia fechada com amplitude curta, sem impacto e sem salto, e fortalece quadril junto — glúteo fraco costuma ser parte do problema. Só comece com liberação do médico ou do fisioterapeuta, e pare qualquer exercício que doer.','[["A — Base sem carga no joelho",[["Rolo no Quadríceps","A",1,"60 s",30],["Rolo na Banda Iliotibial","A",1,"60 s",30],["Ponte de Glúteo no Solo","V",3,"12",45],["Abdução de Quadril com Elástico","V",3,"15",45],["Elevação de Perna Deitado de Lado","V",3,"15 cada lado",45],["Agachamento Isométrico na Parede","V",3,"20-30 s",60],["Panturrilha em Pé","V",3,"15",45],["Alongamento de Quadríceps de Lado","V",1,"30 s cada",30]]],["B — Carga leve e controle",[["Círculos de Tornozelo","A",1,"20 cada",30],["Agachamento na Cadeira (sentar e levantar)","V",3,"10",75],["Leg Press","V",3,"12-15 amplitude curta",75],["Cadeira Flexora","V",3,"12-15",60],["Step-up com Elevação de Joelho","V",3,"10 cada perna",60],["Cadeira Extensora","V",3,"15 amplitude curta",60],["Prancha","V",3,"30 s",45]]],["C — Quadril e equilíbrio",[["Abdução com Elástico","A",2,"20",45],["Elevação Pélvica com Elástico","V",3,"15",60],["Extensão de Quadril com Elástico","V",3,"15 cada perna",45],["Afundo Estático (Split Squat)","V",3,"8 cada perna",75],["Cadeira Abdutora","V",3,"15-20",45],["Alongamento de Flexor do Quadril","V",1,"30 s cada",30],["Alongamento de Posterior Sentado","V",1,"30 s cada",30]]]]'::jsonb),
('Coluna lombar — estabilização (3x por semana)','Reabilitação','Iniciante',3,'Para lombalgia e pós-hérnia já liberada. A lógica é a de Stuart McGill: fortalecer o tronco mantendo a coluna neutra, sem flexionar repetidamente. Nada de abdominal com tronco enrolado nem de terra pesado no começo. Só comece com liberação do médico ou do fisioterapeuta, e pare qualquer exercício que doer.','[["A — Estabilidade e respiração",[["Gato e Camelo","A",1,"10 lentos",30],["Báscula de Pelve em Pé","A",2,"10",30],["Dead Bug (Inseto Morto)","V",3,"8 cada lado",60],["Prancha Lateral com Apoio","V",3,"20-30 s cada",45],["Ponte de Glúteo no Solo","V",3,"12",45],["Superman no Solo","V",3,"10",45],["Postura da Criança","V",1,"45 s",30]]],["B — Quadril forte tira carga da lombar",[["Rolo no Piriforme","A",1,"60 s cada",30],["Elevação Pélvica com Elástico","V",3,"15",60],["Abdução de Quadril com Elástico","V",3,"15",45],["Agachamento na Cadeira (sentar e levantar)","V",3,"10",75],["Bom dia com Elástico","V",3,"12",60],["Prancha","V",3,"30 s",45],["Um Joelho ao Peito","V",1,"30 s cada",30]]],["C — Carga controlada",[["Báscula de Pelve para Ponte","A",2,"10",30],["Leg Press","V",3,"12-15",90],["Puxada Frente","V",3,"12",75],["Remada Baixa","V",3,"12",75],["Hiperextensão sem Banco","V",3,"12",60],["Caminhada do Fazendeiro","V",3,"30 s",60],["Rolo na Lombar","V",1,"60 s",30]]]]'::jsonb),
('Quadril — glúteo médio e estabilidade (3x por semana)','Reabilitação','Iniciante',3,'Para dor lateral de quadril, bursite e impacto femoroacetabular já avaliados. Prioriza abdutores e rotadores, que quase sempre estão fracos, e evita amplitude que belisca a articulação. Só comece com liberação do médico ou do fisioterapeuta, e pare qualquer exercício que doer.','[["A — Ativação de abdutores",[["Rolo no Piriforme","A",1,"60 s cada",30],["Abdução com Elástico","V",3,"20",45],["Elevação de Perna Deitado de Lado","V",3,"15 cada",45],["Círculos de Quadril em Prono","V",2,"10 cada",45],["Ponte de Glúteo no Solo","V",3,"15",45],["Prancha Lateral com Apoio","V",3,"20 s cada",45],["Alongamento de Piriforme (4 sentado)","V",1,"30 s cada",30]]],["B — Força em pé",[["Abdução de Quadril com Elástico","A",2,"20",45],["Agachamento Goblet","V",3,"10-12",90],["Abdução em Pé","V",3,"15 cada",45],["Cadeira Abdutora","V",4,"15-20",45],["Step-up com Elevação de Joelho","V",3,"10 cada perna",60],["Cadeira Flexora","V",3,"12",60]]],["C — Integração",[["Círculos de Quadril em Pé","A",1,"15 cada",30],["Elevação Pélvica com Barra","V",4,"10-12",90],["Afundo Estático (Split Squat)","V",3,"10 cada perna",75],["Pull Through na Polia","V",3,"12-15",60],["Adução de Quadril com Elástico","V",3,"15 cada",45],["Alongamento de Flexor do Quadril","V",1,"30 s cada",30]]]]'::jsonb),
('Ombro — manguito rotador (3x por semana)','Reabilitação','Iniciante',3,'Para síndrome do impacto e tendinopatia de manguito já liberadas. Rotadores e escápula primeiro, elevação acima da cabeça só quando não doer mais. Carga baixa e movimento lento valem mais que peso aqui. Só comece com liberação do médico ou do fisioterapeuta, e pare qualquer exercício que doer.','[["A — Rotadores e escápula",[["Círculos de Ombro","A",1,"15",30],["Rotação Externa com Elástico","V",3,"15 cada",45],["Rotação Interna com Elástico","V",3,"15 cada",45],["Abrir Elástico à Frente (Pull Apart)","V",3,"15",45],["Face Pull","V",3,"15",45],["Alongamento de Peitoral na Porta","V",1,"30 s",30]]],["B — Costas dá base para o ombro",[["Rolo nos Romboides","A",1,"60 s",30],["Remada Baixa","V",3,"12-15",60],["Puxada Triângulo","V",3,"12",60],["Crucifixo Inverso com Elástico","V",3,"15",45],["Encolhimento (Trapézio)","V",3,"12-15",45],["Isometria Cervical Lateral","V",2,"20 s cada",30]]],["C — Volta a empurrar",[["Abrir Elástico à Frente (Pull Apart)","A",2,"15",45],["Flexão de Braço Inclinada","V",3,"10-12",60],["Supino com Elástico","V",3,"12-15",60],["Desenvolvimento com Elástico","V",3,"12-15",60],["Elevação Lateral com Elástico","V",3,"15",45],["Alongamento de Dorsal em Pé","V",1,"30 s cada",30]]]]'::jsonb),
('Volta ao treino depois de parar (3x por semana)','Adaptação','Iniciante',3,'Para quem ficou meses parado, teve alta de uma lesão ou voltou de uma cirurgia liberada. Duas a quatro semanas de recondicionamento com carga baixa, amplitude confortável e nenhuma série até a falha.','[["A — Corpo inteiro leve",[["Esteira","A",1,"8 min",0],["Círculos de Ombro","A",1,"15",30],["Agachamento na Cadeira (sentar e levantar)","V",3,"12",75],["Supino Máquina","V",3,"12-15",75],["Puxada Frente","V",3,"12-15",75],["Ponte de Glúteo no Solo","V",3,"15",45],["Prancha","V",3,"20-30 s",45]]],["B — Corpo inteiro leve",[["Bicicleta","A",1,"8 min",0],["Leg Press","V",3,"12-15",75],["Remada Máquina","V",3,"12-15",75],["Desenvolvimento Máquina","V",3,"12-15",75],["Cadeira Flexora","V",3,"12-15",60],["Panturrilha no Leg","V",3,"15",45],["Dead Bug (Inseto Morto)","V",3,"8 cada lado",45]]],["C — Mobilidade e base",[["Gato e Camelo","A",1,"10",30],["Maior Alongamento do Mundo","V",2,"5 cada lado",45],["Agachamento Goblet","V",3,"10",75],["Elevação Pélvica com Elástico","V",3,"15",60],["Abdução com Elástico","V",3,"20",45],["Face Pull","V",3,"15",45],["Alongamento de Posterior Sentado","V",1,"30 s cada",30]]]]'::jsonb),
('Mobilidade diária — 15 minutos','Mobilidade','Iniciante',1,'Sequência curta para fazer todo dia ou antes do treino: solta quadril, coluna torácica, ombro e tornozelo. Serve como aquecimento de qualquer ficha e como treino de descanso ativo.','[["Sequência completa — 15 minutos",[["Gato e Camelo","V",1,"10 lentos",20],["Círculos de Ombro","V",1,"15 para cada lado",20],["Círculos de Braço","V",1,"15 para cada lado",20],["Rotação de Tronco Sentado","V",1,"10 cada lado",20],["Cachorro Olhando para Baixo (Groiners)","V",1,"8 cada lado",20],["Maior Alongamento do Mundo","V",1,"6 cada lado",20],["Avanço Cruzado (mobilidade)","V",1,"8 cada lado",20],["Círculos de Quadril em Pé","V",1,"12 cada lado",20],["Círculos de Tornozelo","V",1,"15 cada pé",20],["Alongamento de Flexor do Quadril","V",1,"30 s cada",20],["Alongamento de Posterior 90/90","V",1,"30 s cada",20],["Postura da Criança","V",1,"60 s",0]]]]'::jsonb),
('Idoso iniciante — cadeira e elástico (2x por semana)','Idosos','Iniciante',2,'Tudo sentado ou com apoio, sem ir ao chão. O foco é levantar da cadeira sozinho, subir escada e não cair: extensão de quadril e joelho, panturrilha e equilíbrio. Elástico leve, sem prender a respiração.','[["A — Levantar e empurrar",[["Círculos de Ombro","A",1,"10",30],["Círculos de Tornozelo","A",1,"12 cada pé",30],["Agachamento na Cadeira (sentar e levantar)","V",3,"8-10",90],["Panturrilha em Pé","V",3,"12 com apoio",60],["Supino com Elástico","V",2,"12",60],["Desenvolvimento com Elástico","V",2,"10",60],["Abrir Elástico à Frente (Pull Apart)","V",2,"12",45],["Alongamento de Panturrilha na Parede","V",1,"30 s cada",30]]],["B — Puxar e equilibrar",[["Círculos de Braço","A",1,"10 cada lado",30],["Agachamento na Cadeira (sentar e levantar)","V",3,"8-10",90],["Remada Baixa","V",2,"12",60],["Abdução com Elástico","V",2,"12 cada perna",45],["Extensão de Quadril com Elástico","V",2,"12 cada perna",45],["Ponte de Glúteo no Solo","V",2,"10",60],["Rosca Direta","V",2,"12 leve",45],["Alongamento de Quadríceps de Lado","V",1,"30 s cada",30]]]]'::jsonb),
('Idoso — força e equilíbrio (3x por semana)','Idosos','Intermediário',3,'Para o idoso que já treina e tolera carga. Mantém o padrão de sentar e levantar, entra no leg press e na puxada, e reserva um bloco só de equilíbrio e passada. Volume moderado, nada até a falha.','[["A — Pernas",[["Bicicleta","A",1,"6 min",0],["Agachamento na Cadeira (sentar e levantar)","V",3,"10-12",90],["Leg Press","V",3,"12-15",90],["Cadeira Flexora","V",3,"12",60],["Panturrilha no Leg","V",3,"15",45],["Ponte de Glúteo no Solo","V",3,"12",60]]],["B — Tronco e braços",[["Círculos de Ombro","A",1,"12",30],["Puxada Frente","V",3,"12",75],["Supino Máquina","V",3,"12",75],["Remada Máquina","V",3,"12",75],["Desenvolvimento com Elástico","V",3,"12",60],["Rosca Direta","V",2,"12",45],["Tríceps Corda","V",2,"12",45]]],["C — Equilíbrio e caminhada",[["Esteira","A",1,"10 min",0],["Step-up com Elevação de Joelho","V",3,"8 cada perna",75],["Afundo Estático (Split Squat)","V",2,"8 cada perna com apoio",75],["Abdução com Elástico","V",3,"15",45],["Caminhada do Fazendeiro","V",3,"20 s",60],["Panturrilha em Pé","V",3,"15",45],["Alongamento de Posterior Sentado","V",1,"30 s cada",30]]]]'::jsonb),
('Em casa sem equipamento (3x por semana)','Em casa','Iniciante',3,'Só peso do corpo, chão e uma cadeira. Progride pela repetição e pela altura do apoio: quanto mais baixo o apoio da flexão, mais difícil ela fica.','[["A — Inferiores",[["Polichinelo (Star Jump)","A",1,"60 s",30],["Agachamento Livre sem Peso","V",4,"15",60],["Afundo Estático (Split Squat)","V",3,"12 cada perna",60],["Ponte de Glúteo no Solo","V",4,"15",45],["Elevação de Perna Lateral no Solo","V",3,"15 cada",45],["Panturrilha em Pé","V",4,"20",45],["Prancha","V",3,"30 s",45]]],["B — Superiores",[["Círculos de Braço","A",1,"20",30],["Flexão de Braço Inclinada","V",4,"10-15",60],["Flexão de Braço Fechada","V",3,"8-12",60],["Mergulho no Banco","V",3,"10-15",60],["Superman no Solo","V",3,"12",45],["Prancha Lateral com Apoio","V",3,"25 s cada",45],["Dead Bug (Inseto Morto)","V",3,"10 cada lado",45]]],["C — Corpo inteiro e ritmo",[["Corrida Estacionária (Skipping)","A",1,"60 s",30],["Agachamento com Salto","V",3,"12",45],["Flexão de Braço Aberta","V",3,"até a falha",45],["Minhoca (Inchworm)","V",3,"8",45],["Escalador (Spider Crawl)","V",3,"30 s",45],["Abdominal Bicicleta","V",3,"20",45],["Subida no Degrau","V",3,"12 cada perna",45]]]]'::jsonb),
('Em casa com elástico (3x por semana)','Em casa','Iniciante',3,'Um elástico de resistência resolve o que falta no treino de casa: puxar e trabalhar ombro e glúteo com carga. Aumente a dificuldade encurtando o elástico, não só trocando de faixa.','[["A — Empurrar",[["Abrir Elástico à Frente (Pull Apart)","A",2,"15",45],["Supino com Elástico","V",4,"12-15",60],["Desenvolvimento com Elástico","V",3,"12",60],["Crossover com Elástico","V",3,"15",45],["Elevação Lateral com Elástico","V",3,"15",45],["Tríceps Sobre a Cabeça com Elástico","V",3,"12-15",45],["Prancha","V",3,"40 s",45]]],["B — Puxar",[["Círculos de Ombro","A",1,"15",30],["Remada Baixa","V",4,"12-15",60],["Barra Fixa com Elástico","V",3,"até a falha",90],["Crucifixo Inverso com Elástico","V",3,"15",45],["Face Pull","V",3,"15",45],["Rosca Direta","V",3,"12-15",45],["Superman no Solo","V",3,"12",45]]],["C — Pernas e glúteo",[["Abdução de Quadril com Elástico","A",2,"20",45],["Agachamento com Elástico","V",4,"15",60],["Elevação Pélvica com Elástico","V",4,"15",60],["Extensão de Quadril com Elástico","V",3,"15 cada perna",45],["Bom dia com Elástico","V",3,"12-15",60],["Adução de Quadril com Elástico","V",3,"15 cada",45],["Panturrilha com Elástico","V",4,"20",45]]]]'::jsonb),
('Em casa em 20 minutos (2x por semana)','Em casa','Iniciante',2,'Para a semana que não cabe treino. Corpo inteiro, descanso curto, dois circuitos de 20 minutos. Melhor do que não treinar — e mantém o hábito de pé.','[["A — Circuito de 20 minutos",[["Polichinelo (Star Jump)","A",1,"60 s",20],["Agachamento Livre sem Peso","V",3,"20",30],["Flexão de Braço Inclinada","V",3,"12",30],["Ponte de Glúteo no Solo","V",3,"20",30],["Prancha","V",3,"40 s",30],["Escalador (Spider Crawl)","V",3,"30 s",30]]],["B — Circuito de 20 minutos",[["Corrida Estacionária (Skipping)","A",1,"60 s",20],["Afundo Estático (Split Squat)","V",3,"12 cada perna",30],["Mergulho no Banco","V",3,"12",30],["Elevação de Perna Lateral no Solo","V",3,"15 cada",30],["Abdominal Bicicleta","V",3,"20",30],["Superman no Solo","V",3,"15",30]]]]'::jsonb),
('Bumbum na nuca — glúteo em ênfase (4x por semana)','Glúteo','Intermediário',4,'Dois dias de glúteo por semana, porque volume semanal por grupo é o que mais pesa na hipertrofia. Cada dia combina um movimento de extensão de quadril pesado (elevação pélvica, terra sumô), um de agachar e um de abdução — as três funções do glúteo. Amplitude completa e apertar em cima.','[["A — Glúteo pesado",[["Abdução de Quadril com Elástico","A",2,"20",45],["Elevação Pélvica com Barra","V",4,"8-10",120],["Levantamento Terra Sumô","V",4,"8-10",120],["Agachamento Búlgaro","V",3,"10 cada perna",90],["Cadeira Abdutora","V",4,"15-20",45],["Coice Unilateral na Polia","V",3,"12 cada perna",45],["Panturrilha em Pé","V",3,"15-20",45]]],["B — Superiores",[["Puxada Frente","A",2,"12 leve",60],["Puxada Frente","V",4,"10-12",75],["Remada Baixa","V",3,"12",60],["Supino Inclinado com Halteres","V",3,"10-12",75],["Elevação Lateral","V",4,"15",45],["Face Pull","V",3,"15",45],["Tríceps Corda","V",3,"12-15",45],["Prancha","V",3,"45 s",45]]],["C — Glúteo e posterior",[["Abdução com Elástico","A",2,"20",45],["Levantamento Terra Romeno","V",4,"8-12",120],["Elevação Pélvica com Barra","V",4,"12-15",90],["Mesa Flexora","V",4,"12-15",60],["Pull Through na Polia","V",3,"15",60],["Abdução em Pé","V",3,"15 cada",45],["Abdominal na Polia","V",3,"15",45]]],["D — Quadríceps e ombro",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Livre","V",4,"10-12",120],["Leg Press","V",4,"12-15 pé alto",90],["Passada (Walking Lunge)","V",3,"12 cada perna",75],["Cadeira Extensora","V",3,"15",60],["Desenvolvimento com Halteres","V",3,"10-12",75],["Elevação Lateral","V",4,"15-20",45]]]]'::jsonb),
('Glúteo sem agachar — para quem tem dor no joelho (3x por semana)','Glúteo','Iniciante',3,'Todo o trabalho de glúteo feito por extensão e abdução de quadril, sem agachamento profundo, sem afundo e sem impacto. Serve para quem tem dor patelar e ainda quer treinar glúteo com carga.','[["A — Extensão de quadril",[["Abdução de Quadril com Elástico","A",2,"20",45],["Elevação Pélvica com Barra","V",4,"10-12",90],["Ponte de Glúteo no Solo","V",3,"15",45],["Extensão de Quadril com Elástico","V",3,"15 cada perna",45],["Coice na Polia","V",3,"12 cada perna",45],["Mesa Flexora","V",3,"12-15",60]]],["B — Abdução e rotação",[["Abdução com Elástico","A",2,"20",45],["Cadeira Abdutora","V",4,"15-20",45],["Abdução em Pé","V",3,"15 cada",45],["Elevação de Perna Deitado de Lado","V",3,"15 cada",45],["Elevação Pélvica Unilateral","V",3,"12 cada perna",60],["Prancha Lateral com Apoio","V",3,"25 s cada",45]]],["C — Posterior e core",[["Rolo no Posterior de Coxa","A",1,"60 s",30],["Levantamento Terra Romeno","V",4,"10-12",90],["Pull Through na Polia","V",3,"15",60],["Cadeira Flexora","V",3,"12-15",60],["Adução de Quadril com Elástico","V",3,"15 cada",45],["Dead Bug (Inseto Morto)","V",3,"10 cada lado",45],["Alongamento de Glúteo Deitado","V",1,"30 s cada",30]]]]'::jsonb),
('Feminino iniciante — corpo inteiro (3x por semana)','Adaptação','Iniciante',3,'Primeiro ciclo de quem nunca treinou: aprender os padrões (agachar, empurrar, puxar, articular o quadril) com carga leve, e já com um bloco de glúteo em todas as sessões. Sem exercício de máquina demais — o corpo precisa aprender a se sustentar.','[["A — Corpo inteiro",[["Esteira","A",1,"6 min",0],["Agachamento Goblet","V",3,"12",90],["Supino Máquina","V",3,"12",75],["Puxada Frente","V",3,"12",75],["Elevação Pélvica com Elástico","V",3,"15",60],["Abdução com Elástico","V",3,"20",45],["Prancha","V",3,"25 s",45]]],["B — Corpo inteiro",[["Bicicleta","A",1,"6 min",0],["Leg Press","V",3,"12-15",90],["Remada Máquina","V",3,"12",75],["Desenvolvimento com Halteres","V",3,"12",75],["Cadeira Flexora","V",3,"12",60],["Ponte de Glúteo no Solo","V",3,"15",45],["Dead Bug (Inseto Morto)","V",3,"8 cada lado",45]]],["C — Ênfase inferior",[["Abdução de Quadril com Elástico","A",2,"20",45],["Agachamento na Cadeira (sentar e levantar)","V",3,"12",75],["Elevação Pélvica com Barra","V",3,"12",90],["Step-up com Elevação de Joelho","V",3,"10 cada perna",60],["Cadeira Abdutora","V",3,"15-20",45],["Panturrilha em Pé","V",3,"15",45],["Alongamento de Flexor do Quadril","V",1,"30 s cada",30]]]]'::jsonb),
('Glúteo e pernas avançado — pico de volume (4x por semana)','Glúteo','Avançado',4,'Para aluna que já treina há tempo e precisa de mais estímulo: séries pesadas seguidas de séries longas no mesmo grupo, com trabalho de abdução em quase todo dia. Use por 4 a 6 semanas e depois reduza o volume.','[["A — Glúteo pesado",[["Abdução de Quadril com Elástico","A",2,"25",45],["Elevação Pélvica com Barra","V",5,"6-8",150],["Levantamento Terra Sumô","V",4,"6-8",150],["Agachamento Búlgaro","V",4,"10 cada perna",90],["Cadeira Abdutora","V",5,"20",45],["Coice Unilateral na Polia","V",4,"15 cada perna",45]]],["B — Quadríceps",[["Cadeira Extensora","A",2,"20 leve",60],["Agachamento Livre","V",5,"6-10",150],["Agachamento Hack","V",4,"10-12",120],["Leg Press","V",4,"15-20",90],["Passada (Walking Lunge)","V",3,"14 cada perna",90],["Cadeira Extensora","V",4,"15-20",60],["Panturrilha em Pé","V",4,"15",45]]],["C — Posterior e glúteo",[["Rolo no Posterior de Coxa","A",1,"60 s",30],["Levantamento Terra Romeno","V",5,"8-10",150],["Mesa Flexora","V",4,"10-12",75],["Elevação Pélvica com Barra","V",4,"15",75],["Pull Through na Polia","V",4,"15",60],["Cadeira Flexora","V",4,"15",60],["Panturrilha Sentado","V",4,"20",45]]],["D — Superiores e core",[["Puxada Frente","A",2,"12 leve",60],["Barra Fixa com Elástico","V",4,"até a falha",90],["Remada Serrote","V",4,"10-12",75],["Supino Inclinado com Halteres","V",4,"10-12",75],["Desenvolvimento com Halteres","V",3,"10-12",75],["Elevação Lateral","V",5,"15-20",40],["Face Pull","V",4,"15",45],["Abdominal na Polia","V",4,"15",45]]]]'::jsonb)
)
insert into public.train_ficha_modelo (nome,objetivo,nivel,dias,resumo,divisoes)
select s.nome,s.objetivo,s.nivel,s.dias,s.resumo,
  (select jsonb_agg(jsonb_build_object(
     'nome', dv->>0, 'ordem', di-1,
     'exercicios', (select jsonb_agg(jsonb_build_object(
         'nome', ex->>0,
         'tipo_serie', case ex->>1 when 'A' then 'Aquecimento' else 'Valida' end,
         'qtd_series', (ex->>2)::int,
         'faixa_reps', ex->>3,
         'intervalo_seg_min', (ex->>4)::int,
         'ordem', ei-1) order by ei)
       from jsonb_array_elements(dv->1) with ordinality t(ex,ei))
   ) order by di)
   from jsonb_array_elements(s.d) with ordinality u(dv,di))
from src s
where not exists (select 1 from public.train_ficha_modelo f
                   where f.coach_id is null and f.nome = s.nome);
